apiVersion: v1
kind: Service
metadata:
  name: resto-avis-service
spec:
  type: NodePort   # only if you want external access
  selector:
    app: resto-avis
  ports:
    - port: 3000        # internal cluster port
      targetPort: 3000  # container port
      nodePort: 30008   # external port (must be unique)